branch-defaults:
  default:
    environment: production
    group_suffix: null
  master:
    environment: production
    group_suffix: null
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: Django app
  branch: null
  default_ec2_keyname: mykey
  default_platform: Python 3.12
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
